version: 0.2

env:
  shell: bash
  variables:
    PACKER_VERSION: "1.7.8"
    PACKER_EXE: "/usr/bin/packer/packer"
    PACKER_TEMPLATE_DIR: "packer/"
    PACKER_ZIP: "/usr/bin/packer.zip"

phases:
  install:
    commands:
      - echo "Installing Packer"
      - curl -o $PACKER_ZIP https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
      - unzip $PACKER_ZIP -d /usr/bin/packer
      - chmod a+x $PACKER_EXE
      - ${PACKER_EXE} -v
  pre_build:
    commands:
      - ${PACKER_EXE} init ${PACKER_TEMPLATE_DIR}
      - ${PACKER_EXE} validate ${PACKER_TEMPLATE_DIR}
  build:
    commands:
      - ${PACKER_EXE} build -var build_tag_number=${CODEBUILD_BUILD_NUMBER} ${PACKER_TEMPLATE_DIR}
