---
- name: Turn off auto upgrade
  when: ansible_os_family == "Debian"
  lineinfile:
    dest: /etc/apt/apt.conf.d/10periodic
    regexp: "^APT::Periodic::Unattended-Upgrade "
    line: 'APT::Periodic::Unattended-Upgrade "0";'

- name: Ensure minimum days between password changes is 7 or more
  lineinfile:
    regexp: '^PASS_MIN_DAYS'
    state: present
    path: /etc/login.defs
    line: PASS_MIN_DAYS 30

- name: Ensure password hashing algorithm is SHA-512
  lineinfile:
    regexp: '^ENCRYPT_METHOD'
    state: present
    path: /etc/login.defs
    line: ENCRYPT_METHOD sha512

- name: Ensure password expiration warning days is 7 or more
  lineinfile:
    regexp: '^PASS_WARN_AGE'
    state: present
    path: /etc/login.defs
    line: PASS_WARN_AGE 7

- name: Ensure password expiration is 365 days or less
  lineinfile:
    regexp: '^PASS_MAX_DAYS'
    state: present
    path: /etc/login.defs
    line: PASS_MAX_DAYS 364

- name: Verify all users with a password have password inactive no more than 30 days after password expires
  command: useradd -D -f 30

- name: Ensure default user umask is 027 or more restrictive
  lineinfile:
    regexp: '^UMASK'
    state: present
    path: /etc/login.defs
    line: UMASK 027

- name: Ensure ownership on cron are configured
  command: chown root:root /etc/'{{ item }}' 
  loop:
    - crontab
    - cron.hourly
    - cron.daily
    - cron.weekly
    - cron.monthly
    - cron.d

- name: Ensure permissions on cron are configured
  command: chmod og-rwx /etc/'{{ item }}' 
  loop:
    - crontab
    - cron.hourly
    - cron.daily
    - cron.weekly
    - cron.monthly
    - cron.d

- name: Ensure rsync service is not enabled
  systemd:
    name: rsync
    state: stopped

- name: 1.2.3 Ensure gpgcheck is globally activated
  lineinfile:
    regexp: ^gpgcheck
    state: present
    path: /etc.zypp/zypp.conf
    line: gpgcheck=1

- name: Find all of the files inside this directory - zypp package manager config files
  find:
    paths: "/etc/yum.repos.d/"
    patterns: "*.repo"
  register: repos

- name: Ensure gpgcheck is globally activated child zypp package manager config files
  lineinfile:
    regexp: ^gpgcheck
    state: present
    path: /etc.zypp/zypp.conf
    line: gpgcheck=1
  with_items: "{{ repos.files }}"
