- name: Ensure noexec option set on /dev/shm partition - stop executing binaries or executable code in shared memory
  lineinfile:
    regexp: \s/dev/shm\s
    state: present
    path: /etc/fstab
    line: tmpfs /dev/shm tmpfs defaults,noexec,nodev,nosuid,size=2G 0 0

- name: Ensure /dev/shm is configured remount
  command: mount -o remount,noexec,nodev,nosuid /dev/shm

- name: Remove unneeded filesystem types
  lineinfile:
    create: yes
    path: /etc/modprobe.d/{{ item }}.conf
    state: present
    line: install {{ item }} /bin/true
  loop:
    - cramfs
    - freevxfs
    - jffs2
    - hfs
    - hfsplus
    - squashfs
    - udf
    - FAT

- name: Remove unneeded filesystem types modprobe
  command: modprobe -r {{ item }}
  loop:
    - cramfs
    - freevxfs
    - jffs2
    - hfs
    - hfsplus
    - squashfs
    - udf
    - FAT

- name: Ensure permissions on bootloader config are configured Ubuntu
  command: chmod og-rwx /etc/default/grub

- name: Ensure password reuse is limited
  lineinfile:
    state: present
    path: /etc/pam.d/common-password
    line: password required pam_pwhistory.so remember=5

- name: Ensure /tmp is configured
  lineinfile:
    regexp: ^tmpfs\s\/tmp
    state: present
    path: /etc/fstab
    line: tmpfs /tmp tmpfs defaults,rw,nosuid,nodev,noexec,relatime 0 0

- name: Ensure /tmp is configured remount
  command: mount -o remount,noexec,nodev,nosuid /tmp

- name: Ensure nodev option set on /home partition
  command: mount -o remount,nodev /home

- name: Ensure permissions on bootloader config are configured
  command: chmod og-rwx /voot/grub2/grub.cfg
