---
- name: "[System Functions] Activities Include"
  include_tasks:
    file: sysctl.yml

- name: "[Audit and Logging] Activities Include"
  include_tasks:
    file: audit.yml

- name: "[Core Service Configuration] Activities Include"
  include_tasks:
    file: core_services.yml

- name: "[FileSystem Configuration] Activities Include"
  include_tasks:
    file: file_system.yml

- name: "[SSH Configuration] Activities Include"
  include_tasks:
    file: ssh.yml
