name: Checkov

on: [push]

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Checkov
        uses: docker://bridgecrew/checkov:latest
        with:
          directory: /github/workspace
          quiet: true
          download-external-modules: true
          framework: terraform
