name: Terraform Validate

on: [push]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        working-directory: ./ci-cd
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: ./ci-cd
        run: terraform validate

      - name: Terraform fmt
        working-directory: ./ci-cd
        run: terraform fmt -check
